[project]
name = "flask-todo-app"
version = "0.1.0"
description = "A single-page Flask web application for managing tasks with CSV backend storage"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "Flask>=2.3.0",
    "Werkzeug>=2.3.0",
]